[wokwi]
version = 1
firmware = ".pio/build/megaatmega2560/firmware.hex"
elf = ".pio/build/megaatmega2560/firmware.elf"

[wokwi.club]
key = "JnU9NDQxNzA0NzA3MjUxOTM2MjU3Jm49U29sb2dhbitBcnRlbWlvcyZlPWFydGVtaW9zLnNvbG9nYW4lNDBtaWIudXRtLm1kJng9MjAyNTEyMDIAuMtNCekAptZ1kZyaTta_SevoX6cgu_SYn9Moh1sR_StcS2GbH5X6DvA86xQQoYJAwiBOwuXn3wrXJbkka8M0myygHE7ZYcEKpo6N7nvTjSv2kC7mp4DPM2TidPjEB9nElarJZouml2FcSxHlR9SesMbcJ9JBIa5aIfOBGXq4jjy_Sv0Nm8_Sy5bhaz9V2T3fA8d_P86_PV3PkL52SJ5vxrmYSkOPReNJ5Z9AR1gGlCpy4Gcv1Zm_S1hCfXnZnOUqHi0jvT98PkkTlJxpMGrboZVjLKLzK9RHavfAqQLlv_SgHioMJsXuklxZc21UyzU0ogFVu8xNrGXEgg3brCt_Piiusg5Ni5VA"

